// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
	modules: ['@nuxt/eslint', '@nuxtjs/tailwindcss', '@pinia/nuxt', 'pinia-plugin-persistedstate/nuxt', '@nuxtjs/i18n', '@nuxt/icon'],
	ssr: false,
	devtools: { enabled: false },
	app: {
		baseURL: '/portfolio/',
		head: {
			title: 'Portfolio - David Simón',
			htmlAttrs: {
				lang: 'es',
			},
			meta: [
				{ name: 'description', content: "Welcome to my portfolio! I'm David, a full stack web developer. Explore my work and projects here." },
				{ name: 'author', content: 'David Simón - @DeibidSE' },
				{ name: 'viewport', content: 'width=device-width, initial-scale=1' },
				{ name: 'robots', content: 'noindex, nofollow' },
				{ name: 'theme-color', content: '#9333ea' },
			],
			link: [
				{ rel: 'icon', href: '/portfolio/favicon.ico', sizes: 'any' },
				{ rel: 'icon', type: 'image/x-icon', href: '/portfolio/favicon.ico' },
				{ rel: 'apple-touch-icon', href: '/portfolio/favicons/apple-touch-icon.png' },
				{ rel: 'manifest', href: '/portfolio/favicons/site.webmanifest' },
			],
		},
	},
	css: ['@/assets/css/tailwind.css', '@/assets/css/index.css'],
	runtimeConfig: {
		public: {
			BASE_URL: '/portfolio',
		},
	},
	compatibilityDate: '2026-01-01',
	eslint: {
		config: {
			stylistic: {
				indent: 'tab',
				semi: false,
				quotes: 'single',
			},
		},
	},
	i18n: {
		strategy: 'no_prefix',
		locales: [
			{ code: 'es', language: 'es-ES', name: 'Español', file: 'es.json' },
			{ code: 'en', language: 'en-GB', name: 'English', file: 'en.json' },
		],
		defaultLocale: 'es',
	},
	icon: {
		mode: 'svg',
		provider: 'none',
		clientBundle: {
			icons: [
				'circle-flags:en',
				'circle-flags:es',
				'logos:bitbucket',
				'logos:docker-icon',
				'logos:html-5',
				'logos:javascript',
				'logos:jira',
				'logos:laravel',
				'logos:mysql',
				'logos:nuxt-icon',
				'logos:php',
				'logos:pinia',
				'logos:postgresql',
				'logos:swagger',
				'logos:tailwindcss-icon',
				'logos:typescript-icon',
				'logos:vitejs',
				'logos:vue',
				'logos:vuetifyjs',
				'tabler:api',
				'tabler:arrow-bar-to-left',
				'tabler:arrow-left',
				'tabler:arrow-right',
				'tabler:brand-github',
				'tabler:brand-linkedin',
				'tabler:briefcase',
				'tabler:chevron-down',
				'tabler:chevron-up',
				'tabler:code',
				'tabler:dots-vertical',
				'tabler:external-link',
				'tabler:home',
				'tabler:lock',
				'tabler:mail',
				'tabler:map-pin',
				'tabler:message-2-code',
				'tabler:moon',
				'tabler:refresh',
				'tabler:sun',
				'tabler:user',
				'tabler:world-www',
				'vscode-icons:file-type-css',
				'vscode-icons:file-type-cursorrules',
				'vscode-icons:file-type-git',
				'vscode-icons:file-type-postman',
				'vscode-icons:file-type-vscode',
			],
			includeCustomCollections: true,
		},
		customCollections: [
			{
				prefix: 'my-icon',
				dir: './app/assets/icons',
			},
		],
	},
})
